# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UpperMachine.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CamShow(object):
    def setupUi(self, CamShow):
        CamShow.setObjectName("CamShow")
        CamShow.resize(1527, 947)
        CamShow.setToolTipDuration(-2)
        self.centralwidget = QtWidgets.QWidget(CamShow)
        self.centralwidget.setObjectName("centralwidget")
        self.SettingFm = QtWidgets.QFrame(self.centralwidget)
        self.SettingFm.setGeometry(QtCore.QRect(760, 40, 751, 551))
        self.SettingFm.setFrameShape(QtWidgets.QFrame.Box)
        self.SettingFm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SettingFm.setObjectName("SettingFm")
        self.label_binary = QtWidgets.QLabel(self.SettingFm)
        self.label_binary.setGeometry(QtCore.QRect(30, 30, 641, 481))
        self.label_binary.setFrameShape(QtWidgets.QFrame.Box)
        self.label_binary.setObjectName("label_binary")
        self.DispFm = QtWidgets.QFrame(self.centralwidget)
        self.DispFm.setGeometry(QtCore.QRect(20, 20, 641, 791))
        self.DispFm.setFrameShape(QtWidgets.QFrame.Box)
        self.DispFm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DispFm.setObjectName("DispFm")
        self.Bt_begin = QtWidgets.QPushButton(self.DispFm)
        self.Bt_begin.setGeometry(QtCore.QRect(70, 20, 93, 28))
        self.Bt_begin.setObjectName("Bt_begin")
        self.Bt_pause = QtWidgets.QPushButton(self.DispFm)
        self.Bt_pause.setGeometry(QtCore.QRect(190, 20, 93, 28))
        self.Bt_pause.setObjectName("Bt_pause")
        self.Bt_save = QtWidgets.QPushButton(self.DispFm)
        self.Bt_save.setGeometry(QtCore.QRect(310, 20, 93, 28))
        self.Bt_save.setObjectName("Bt_save")
        self.Bt_exit = QtWidgets.QPushButton(self.DispFm)
        self.Bt_exit.setGeometry(QtCore.QRect(430, 20, 93, 28))
        self.Bt_exit.setObjectName("Bt_exit")
        self.FmRateLCD = QtWidgets.QLCDNumber(self.DispFm)
        self.FmRateLCD.setGeometry(QtCore.QRect(80, 740, 71, 31))
        self.FmRateLCD.setObjectName("FmRateLCD")
        self.ImgWidthLCD = QtWidgets.QLCDNumber(self.DispFm)
        self.ImgWidthLCD.setGeometry(QtCore.QRect(430, 740, 71, 31))
        self.ImgWidthLCD.setObjectName("ImgWidthLCD")
        self.ImgHeightLCD = QtWidgets.QLCDNumber(self.DispFm)
        self.ImgHeightLCD.setGeometry(QtCore.QRect(530, 740, 71, 31))
        self.ImgHeightLCD.setObjectName("ImgHeightLCD")
        self.label_2 = QtWidgets.QLabel(self.DispFm)
        self.label_2.setGeometry(QtCore.QRect(10, 750, 72, 15))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.DispFm)
        self.label_3.setGeometry(QtCore.QRect(350, 750, 72, 15))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.DispFm)
        self.label_4.setGeometry(QtCore.QRect(510, 750, 16, 16))
        self.label_4.setObjectName("label_4")
        self.label_pic = QtWidgets.QLabel(self.DispFm)
        self.label_pic.setGeometry(QtCore.QRect(30, 60, 521, 641))
        self.label_pic.setFrameShape(QtWidgets.QFrame.Box)
        self.label_pic.setObjectName("label_pic")
        self.MsgFm = QtWidgets.QFrame(self.centralwidget)
        self.MsgFm.setGeometry(QtCore.QRect(50, 840, 971, 61))
        self.MsgFm.setFrameShape(QtWidgets.QFrame.Box)
        self.MsgFm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MsgFm.setObjectName("MsgFm")
        self.MsgTE = QtWidgets.QTextEdit(self.MsgFm)
        self.MsgTE.setGeometry(QtCore.QRect(20, 10, 921, 41))
        self.MsgTE.setObjectName("MsgTE")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(710, 740, 72, 15))
        self.label.setObjectName("label")
        self.FilePathLE = QtWidgets.QLineEdit(self.centralwidget)
        self.FilePathLE.setGeometry(QtCore.QRect(780, 730, 171, 31))
        self.FilePathLE.setReadOnly(True)
        self.FilePathLE.setObjectName("FilePathLE")
        self.Bt_path = QtWidgets.QPushButton(self.centralwidget)
        self.Bt_path.setGeometry(QtCore.QRect(960, 730, 71, 31))
        self.Bt_path.setObjectName("Bt_path")
        self.TE_abcresult = QtWidgets.QTextEdit(self.centralwidget)
        self.TE_abcresult.setGeometry(QtCore.QRect(810, 620, 291, 51))
        self.TE_abcresult.setObjectName("TE_abcresult")
        self.LCD_imindex = QtWidgets.QLCDNumber(self.centralwidget)
        self.LCD_imindex.setGeometry(QtCore.QRect(1130, 620, 71, 31))
        self.LCD_imindex.setObjectName("LCD_imindex")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(720, 640, 72, 15))
        self.label_5.setObjectName("label_5")
        self.label_abc = QtWidgets.QLabel(self.centralwidget)
        self.label_abc.setGeometry(QtCore.QRect(1100, 690, 291, 51))
        self.label_abc.setFrameShape(QtWidgets.QFrame.Box)
        self.label_abc.setObjectName("label_abc")
        CamShow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CamShow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1527, 26))
        self.menubar.setObjectName("menubar")
        CamShow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CamShow)
        self.statusbar.setObjectName("statusbar")
        CamShow.setStatusBar(self.statusbar)

        self.retranslateUi(CamShow)
        QtCore.QMetaObject.connectSlotsByName(CamShow)

    def retranslateUi(self, CamShow):
        _translate = QtCore.QCoreApplication.translate
        CamShow.setWindowTitle(_translate("CamShow", "CamShow"))
        self.label_binary.setText(_translate("CamShow", "TextLabel"))
        self.Bt_begin.setText(_translate("CamShow", "开始"))
        self.Bt_pause.setText(_translate("CamShow", "暂停"))
        self.Bt_save.setText(_translate("CamShow", "保存"))
        self.Bt_exit.setText(_translate("CamShow", "退出"))
        self.label_2.setText(_translate("CamShow", "当前帧率"))
        self.label_3.setText(_translate("CamShow", "图像尺寸："))
        self.label_4.setText(_translate("CamShow", "×"))
        self.label_pic.setText(_translate("CamShow", "label_pic"))
        self.label.setText(_translate("CamShow", "文件路径"))
        self.Bt_path.setText(_translate("CamShow", "..."))
        self.label_5.setText(_translate("CamShow", "识别结果"))
        self.label_abc.setText(_translate("CamShow", "TextLabel"))

